-- AlterTable
ALTER TABLE `claims` ADD COLUMN `presentationScheduledAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('TASK_ASSIGNED', 'MESSAGE_POSTED', 'MEETING_SCHEDULED', 'DOCUMENT_UPLOADED', 'HOSTING_REQUEST', 'EVENT_UPDATE') NOT NULL;

